import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="text-lg">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className="text-xl">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className="text-2xl">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className="text-3xl">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
